n = str(input('Por favor, digite seu nome completo: ')).strip()
nome = n.split()
print('\nMuito prazer em te conhecer')
print('Seu primeiro nome é {}'.format(nome[0]))
print('Seu ultimo nome é {}'.format(nome[len(nome)-1]))